### 验证码
GET http://localhost:8080/dev-api/v1/third/generateCaptcha
    ?bizType=BizCaptchaLogin&type=1

### 登录
POST http://localhost:8080/dev-api/v1/auth/login

{
    "username": "careful",
    "password": "123456",
    "id": "AFFOGT4YCS3Y93qqM6Bz",
    "code": "954189",
    "bizType": "BizCaptchaLogin"
}