### 验证码
GET http://localhost:8080/dev-api/v1/third/generateCaptcha
    ?bizType=BizCaptchaLogin&type=1

### 登录
POST http://localhost:8080/dev-api/v1/auth/login

{
    "username": "careful",
    "password": "123456",
    "id": "dk1sjQtn3Ff0hRn81OnD",
    "code": "180449",
    "bizType": "BizCaptchaLogin"
}