### 删除
DELETE http://localhost:8080/dev-api/v1/tools/bucket/delete/E1F5B042-DAF1-4EF3-AA90-288A29A4408F
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTI1NjU4NjEsIm5iZiI6MTc1MjU2MjI2MSwiaWF0IjoxNzUyNTYyMjYxLCJ1c2VySWQiOiJFMUU5QzYwQS0zMTRBLTQzNjItODQ0NS1EQjZFMjg3NjYxMEQiLCJ1c2VybmFtZSI6ImNhcmVmdWwiLCJ1c2VyVHlwZSI6MSwidXNlckFnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2In0.4r1JqH34Vbn2X0_C6xT5vmJxkam_tixG1fZXUZ0xxtA

### 批量删除
POST http://localhost:8080/dev-api/v1/tools/bucket/delete/batchDelete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTI1NjU4NjEsIm5iZiI6MTc1MjU2MjI2MSwiaWF0IjoxNzUyNTYyMjYxLCJ1c2VySWQiOiJFMUU5QzYwQS0zMTRBLTQzNjItODQ0NS1EQjZFMjg3NjYxMEQiLCJ1c2VybmFtZSI6ImNhcmVmdWwiLCJ1c2VyVHlwZSI6MSwidXNlckFnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2In0.4r1JqH34Vbn2X0_C6xT5vmJxkam_tixG1fZXUZ0xxtA

[
  "E29A5F4F-C9E5-4D3F-B24C-10449B0B8B33",
  "59D689A5-7324-4977-8B21-F20ED0BCA3EC",
  "7E2AFE42-6328-4036-B2F3-5FF04FC6DD25"
]

### 根据ID查询
GET http://localhost:8080/dev-api/v1/tools/bucket/getById/ED934E35-3AB7-468D-AF45-461C224AD222
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTI2MzU4MzAsIm5iZiI6MTc1MjYzMjIzMCwiaWF0IjoxNzUyNjMyMjMwLCJ1c2VySWQiOiJFMUU5QzYwQS0zMTRBLTQzNjItODQ0NS1EQjZFMjg3NjYxMEQiLCJ1c2VybmFtZSI6ImNhcmVmdWwiLCJ1c2VyVHlwZSI6MSwidXNlckFnZW50IjoiSW50ZWxsaUogSFRUUCBDbGllbnQvR29MYW5kIDIwMjQuMyJ9.H6jXrT6h4s5LYvFblihe1Bw-yiEFeJ5w7NHoT_HAcWQ