// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "CJiaの用心",
            "url": "http://www.swagger.io/support",
            "email": "2224693191@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/password-login": {
            "post": {
                "description": "图形验证码密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "图形验证码密码登录",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/password-register": {
            "post": {
                "description": "账号密码注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "账号密码注册",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "RegisterRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/third/generateCaptcha": {
            "get": {
                "description": "生成指定业务验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "第三方业务管理"
                ],
                "summary": "生成指定业务验证码",
                "parameters": [
                    {
                        "enum": [
                            "BizCaptchaLogin"
                        ],
                        "type": "string",
                        "x-enum-comments": {
                            "BizTypeCaptchaLogin": "验证码密码登录"
                        },
                        "x-enum-varnames": [
                            "BizTypeCaptchaLogin"
                        ],
                        "description": "业务类型",
                        "name": "bizType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1
                        ],
                        "type": "integer",
                        "x-enum-comments": {
                            "DigitIotaCaptcha": "数字字母验证码"
                        },
                        "x-enum-varnames": [
                            "DigitIotaCaptcha"
                        ],
                        "description": "验证码类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/third.CaptchaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/batchDelete": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "批量删除字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "批量删除字典",
                "parameters": [
                    {
                        "description": "ID数组",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/create": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "创建字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "创建字典",
                "parameters": [
                    {
                        "description": "字典信息",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tools.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "删除字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "删除字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/getById/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "根据ID获取字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "根据ID获取字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/import": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "导入字典",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "导入字典",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件(支持xlsx/csv格式)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/listAll": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取所有字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "获取所有字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": -1,
                        "description": "字典类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": -1,
                        "description": "字典数据类型",
                        "name": "typeValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/listPage": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "分页获取字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "分页获取字典",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": -1,
                        "description": "字典类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": -1,
                        "description": "字典数据类型",
                        "name": "typeValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/update/{id}": {
            "put": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "更新字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "更新字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "字典信息",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tools.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "bizType",
                "code",
                "id",
                "password",
                "username"
            ],
            "properties": {
                "bizType": {
                    "description": "验证码类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/captcha.BizTypeCaptcha"
                        }
                    ]
                },
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "id": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "username": {
                    "description": "用户账号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "登录令牌",
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "username": {
                    "description": "用户账号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "captcha.BizTypeCaptcha": {
            "type": "string",
            "enum": [
                "BizCaptchaLogin"
            ],
            "x-enum-comments": {
                "BizTypeCaptchaLogin": "验证码密码登录"
            },
            "x-enum-varnames": [
                "BizTypeCaptchaLogin"
            ]
        },
        "captcha.TypeCaptcha": {
            "type": "integer",
            "enum": [
                1
            ],
            "x-enum-comments": {
                "DigitIotaCaptcha": "数字字母验证码"
            },
            "x-enum-varnames": [
                "DigitIotaCaptcha"
            ]
        },
        "dict.TypeConst": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "TypeConst0": "普通字典",
                "TypeConst1": "系统字典",
                "TypeConst2": "枚举字典"
            },
            "x-enum-varnames": [
                "TypeConst0",
                "TypeConst1",
                "TypeConst2"
            ]
        },
        "dict.TypeValueConst": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "TypeValueConst0": "字符串",
                "TypeValueConst1": "整型",
                "TypeValueConst2": "布尔"
            },
            "x-enum-varnames": [
                "TypeValueConst0",
                "TypeValueConst1",
                "TypeValueConst2"
            ]
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                }
            }
        },
        "third.CaptchaResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "id": {
                    "description": "验证码Id",
                    "type": "string"
                },
                "img": {
                    "description": "验证码图片",
                    "type": "string"
                }
            }
        },
        "tools.Request": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "字典编码",
                    "type": "string",
                    "maxLength": 100
                },
                "name": {
                    "description": "字典名称",
                    "type": "string",
                    "maxLength": 100
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "type": {
                    "description": "字典类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dict.TypeConst"
                        }
                    ]
                },
                "typeValue": {
                    "description": "字典类型值",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dict.TypeValueConst"
                        }
                    ]
                },
                "version": {
                    "description": "版本",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "LoginToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/dev-api",
	Schemes:          []string{},
	Title:            "CarefulAdmin",
	Description:      "CarefulAdmin在线接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
