// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "CJiaの用心",
            "url": "http://www.swagger.io/support",
            "email": "2224693191@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "修改当前登录用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码参数",
                        "name": "ChangePasswordRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "账号密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "账号密码登录",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "用户退出登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh-token": {
            "post": {
                "description": "使用旧的JWT令牌获取新的令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌参数",
                        "name": "RefreshTokenRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "RegisterRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/type-login": {
            "post": {
                "description": "不同类型用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "多用户类型登录",
                "parameters": [
                    {
                        "description": "多用户类型登录参数",
                        "name": "UserTypeLoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserTypeLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/userinfo": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/create": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "创建部门",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "创建部门",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "CreateDeptRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.CreateDeptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/listTree": {
            "get": {
                "description": "获取部门树形结构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "获取部门树形结构",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "数据归属部门",
                        "name": "belongDept",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门编码",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.DeptTree"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/menu/listRouter": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取所有菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "获取所有菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "default": -1,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.Menu"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/user/listPage": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取用户分页列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/用户管理"
                ],
                "summary": "获取用户分页列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "数据归属部门",
                        "name": "belongDept",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.UserListPageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/third/generateCaptcha": {
            "get": {
                "description": "生成指定业务验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "第三方业务管理"
                ],
                "summary": "生成指定业务验证码",
                "parameters": [
                    {
                        "type": "string",
                        "example": "BizCaptchaLogin",
                        "description": "业务类型",
                        "name": "bizType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1
                        ],
                        "type": "integer",
                        "x-enum-comments": {
                            "DigitIotaCaptcha": "数字字母验证码"
                        },
                        "x-enum-varnames": [
                            "DigitIotaCaptcha"
                        ],
                        "description": "验证码类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/third.CaptchaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/create": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "创建字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "创建字典",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "CreateDictRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tools.CreateDictRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "删除指定id字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "删除字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/getById/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取指定id字典信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "获取字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_tools.Dict"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/listAll": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取所有字典列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "获取所有字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典分类",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典值类型",
                        "name": "valueType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_tools.Dict"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/listPage": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取字典分页列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "获取字典分页列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典分类",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典值类型",
                        "name": "valueType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.DictListPageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/update": {
            "put": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "更新字典信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "更新字典",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "UpdateDictRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tools.UpdateDictRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "description": "新密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6,
                    "example": "654321"
                },
                "oldPassword": {
                    "description": "旧密码",
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "bizType",
                "code",
                "id",
                "password",
                "username"
            ],
            "properties": {
                "bizType": {
                    "description": "验证码类型",
                    "type": "string",
                    "example": "BizCaptchaLogin"
                },
                "code": {
                    "description": "验证码",
                    "type": "string",
                    "example": "654321"
                },
                "id": {
                    "description": "验证码",
                    "type": "string",
                    "example": "ldqQpBjJfvPxbBzP"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "demo"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "expire": {
                    "description": "过期时间(秒)",
                    "type": "integer"
                },
                "token": {
                    "description": "JWT令牌",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User"
                        }
                    ]
                }
            }
        },
        "auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "description": "旧的JWT令牌",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp..."
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string",
                    "example": ""
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "admin@test.com"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer",
                    "example": 1
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                },
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "管理员"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6,
                    "example": "123456"
                },
                "userType": {
                    "description": "用户类型",
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "demo"
                }
            }
        },
        "auth.UserTypeLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "userType",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "userType": {
                    "description": "用户类型",
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "captcha.TypeCaptcha": {
            "type": "integer",
            "enum": [
                1
            ],
            "x-enum-comments": {
                "DigitIotaCaptcha": "数字字母验证码"
            },
            "x-enum-varnames": [
                "DigitIotaCaptcha"
            ]
        },
        "github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.Menu": {
            "type": "object",
            "properties": {
                "api": {
                    "description": "接口地址",
                    "type": "string"
                },
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "component": {
                    "description": "组件地址",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "icon": {
                    "description": "菜单图标",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "isAffix": {
                    "description": "是否缓存固定路由",
                    "type": "boolean"
                },
                "isFull": {
                    "description": "是否缓存全屏",
                    "type": "boolean"
                },
                "isHide": {
                    "description": "是否隐藏",
                    "type": "boolean"
                },
                "isKeepAlive": {
                    "description": "是否页面缓存",
                    "type": "boolean"
                },
                "isLink": {
                    "description": "是否外链",
                    "type": "boolean"
                },
                "method": {
                    "description": "接口请求方法",
                    "type": "integer"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "组件名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "上级菜单",
                    "type": "string"
                },
                "path": {
                    "description": "路由地址",
                    "type": "string"
                },
                "permission": {
                    "description": "权限标识",
                    "type": "string"
                },
                "redirect": {
                    "description": "重定向地址",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "title": {
                    "description": "菜单标题",
                    "type": "string"
                },
                "type": {
                    "description": "菜单类型",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        },
        "github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept": {
                    "description": "部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "deptId": {
                    "description": "部门ID",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "mobile": {
                    "description": "电话",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userType": {
                    "description": "用户类型",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        },
        "github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_tools.Dict": {
            "type": "object",
            "properties": {
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "字典编码",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "字典名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "type": {
                    "description": "字典分类",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "valueType": {
                    "description": "字典值类型",
                    "type": "integer"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        },
        "github_com_carefuly_carefuly-admin-go-gin_internal_model_careful_system.Dept": {
            "type": "object",
            "properties": {
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "部门编码",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "owner": {
                    "description": "负责人",
                    "type": "string"
                },
                "parent_id": {
                    "description": "上级部门",
                    "type": "string"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                }
            }
        },
        "system.CreateDeptRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "部门编码",
                    "type": "string",
                    "maxLength": 100,
                    "example": "CARE_TEST"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "admin@test.com"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string",
                    "maxLength": 100,
                    "example": "测试部门"
                },
                "owner": {
                    "description": "负责人",
                    "type": "string",
                    "example": "admin"
                },
                "parent_id": {
                    "description": "上级部门",
                    "type": "string",
                    "example": "1"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string",
                    "example": "18566666666"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255,
                    "example": "测试部门"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "system.DeptTree": {
            "type": "object",
            "properties": {
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "children": {
                    "description": "子部门列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/system.DeptTree"
                    }
                },
                "code": {
                    "description": "部门编码",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "owner": {
                    "description": "负责人",
                    "type": "string"
                },
                "parent_id": {
                    "description": "上级部门",
                    "type": "string"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        },
        "system.UserListPageResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "third.CaptchaResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "id": {
                    "description": "验证码Id",
                    "type": "string"
                },
                "img": {
                    "description": "验证码图片",
                    "type": "string"
                }
            }
        },
        "tools.CreateDictRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "字典编码",
                    "type": "string",
                    "maxLength": 100
                },
                "name": {
                    "description": "字典名称",
                    "type": "string",
                    "maxLength": 100
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "type": {
                    "description": "字典分类",
                    "type": "integer",
                    "default": 1
                },
                "valueType": {
                    "description": "字典值类型",
                    "type": "integer",
                    "default": 1
                }
            }
        },
        "tools.DictListPageResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_tools.Dict"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "tools.UpdateDictRequest": {
            "type": "object",
            "required": [
                "code",
                "id",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "字典编码",
                    "type": "string",
                    "maxLength": 100
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "name": {
                    "description": "字典名称",
                    "type": "string",
                    "maxLength": 100
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "Type      int    ` + "`" + `json:\"type\" binding:\"omitempty\" default:\"1\"` + "`" + `      // 字典分类\nValueType int    ` + "`" + `json:\"valueType\" binding:\"omitempty\" default:\"1\"` + "`" + ` // 字典值类型\nStatus  bool   ` + "`" + `json:\"status\" binding:\"omitempty\" default:\"true\"` + "`" + ` // 状态",
                    "type": "integer",
                    "default": 1
                },
                "version": {
                    "description": "版本",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "LoginToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/dev-api",
	Schemes:          []string{},
	Title:            "CarefulAdmin",
	Description:      "CarefulAdmin在线接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
