// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "CJiaの用心",
            "url": "http://www.swagger.io/support",
            "email": "2224693191@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/password-login": {
            "post": {
                "description": "图形验证码密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "图形验证码密码登录",
                "operationId": "PasswordCaptchaLoginHandler",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/password-register": {
            "post": {
                "description": "账号密码注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "账号密码注册",
                "operationId": "PassWordRegisterHandler",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "RegisterRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/third/generateCaptcha": {
            "get": {
                "description": "生成指定业务验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "第三方业务管理"
                ],
                "summary": "生成指定业务验证码",
                "operationId": "GenerateCaptchaHandler",
                "parameters": [
                    {
                        "enum": [
                            "BizCaptchaLogin"
                        ],
                        "type": "string",
                        "x-enum-comments": {
                            "BizTypeCaptchaLogin": "密码登录"
                        },
                        "x-enum-varnames": [
                            "BizTypeCaptchaLogin"
                        ],
                        "description": "业务类型",
                        "name": "bizType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1
                        ],
                        "type": "integer",
                        "x-enum-comments": {
                            "DigitIotaCaptcha": "数字字母验证码"
                        },
                        "x-enum-varnames": [
                            "DigitIotaCaptcha"
                        ],
                        "description": "验证码类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/third.CaptchaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "_const.BizTypeCaptcha": {
            "type": "string",
            "enum": [
                "BizCaptchaLogin"
            ],
            "x-enum-comments": {
                "BizTypeCaptchaLogin": "密码登录"
            },
            "x-enum-varnames": [
                "BizTypeCaptchaLogin"
            ]
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "bizType",
                "code",
                "id",
                "password",
                "username"
            ],
            "properties": {
                "bizType": {
                    "description": "验证码类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/_const.BizTypeCaptcha"
                        }
                    ]
                },
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "id": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "username": {
                    "description": "用户账号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "登录令牌",
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "username": {
                    "description": "用户账号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "captcha.TypeCaptcha": {
            "type": "integer",
            "enum": [
                1
            ],
            "x-enum-comments": {
                "DigitIotaCaptcha": "数字字母验证码"
            },
            "x-enum-varnames": [
                "DigitIotaCaptcha"
            ]
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                }
            }
        },
        "third.CaptchaResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "id": {
                    "description": "验证码Id",
                    "type": "string"
                },
                "img": {
                    "description": "验证码图片",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/dev-api",
	Schemes:          []string{},
	Title:            "CarefulAdmin",
	Description:      "CarefulAdmin在线接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
