basePath: /dev-api
definitions:
  auth.ChangePasswordRequest:
    properties:
      newPassword:
        description: 新密码
        example: "654321"
        maxLength: 20
        minLength: 6
        type: string
      oldPassword:
        description: 旧密码
        example: "123456"
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  auth.LoginRequest:
    properties:
      bizType:
        description: 验证码类型
        example: BizCaptchaLogin
        type: string
      code:
        description: 验证码
        example: "654321"
        type: string
      id:
        description: 验证码
        example: ldqQpBjJfvPxbBzP
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      username:
        description: 用户名
        example: demo
        type: string
    required:
    - bizType
    - code
    - id
    - password
    - username
    type: object
  auth.LoginResponse:
    properties:
      expire:
        description: 过期时间(秒)
        type: integer
      token:
        description: JWT令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User'
        description: 用户信息
    type: object
  auth.RefreshTokenRequest:
    properties:
      token:
        description: 旧的JWT令牌
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp...
        type: string
    required:
    - token
    type: object
  auth.RegisterRequest:
    properties:
      avatar:
        description: 头像
        example: ""
        type: string
      email:
        description: 邮箱
        example: admin@test.com
        type: string
      gender:
        description: 性别
        example: 1
        type: integer
      mobile:
        description: 手机号
        example: "13800138000"
        type: string
      name:
        description: 姓名
        example: 管理员
        maxLength: 20
        minLength: 2
        type: string
      password:
        description: 密码
        example: "123456"
        maxLength: 20
        minLength: 6
        type: string
      userType:
        description: 用户类型
        example: 1
        type: integer
      username:
        description: 用户名
        example: demo
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    - password
    - username
    type: object
  auth.UserTypeLoginRequest:
    properties:
      password:
        description: 密码
        example: "123456"
        type: string
      userType:
        description: 用户类型
        example: 1
        type: integer
      username:
        description: 用户名
        example: admin
        type: string
    required:
    - password
    - userType
    - username
    type: object
  captcha.TypeCaptcha:
    enum:
    - 1
    type: integer
    x-enum-comments:
      DigitIotaCaptcha: 数字字母验证码
    x-enum-varnames:
    - DigitIotaCaptcha
  github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.Menu:
    properties:
      api:
        description: 接口地址
        type: string
      belongDept:
        description: 数据归属部门
        type: string
      component:
        description: 组件地址
        type: string
      createTime:
        description: 创建时间
        type: string
      creator:
        description: 创建人
        type: string
      icon:
        description: 菜单图标
        type: string
      id:
        description: 主键ID
        type: string
      isAffix:
        description: 是否缓存固定路由
        type: boolean
      isFull:
        description: 是否缓存全屏
        type: boolean
      isHide:
        description: 是否隐藏
        type: boolean
      isKeepAlive:
        description: 是否页面缓存
        type: boolean
      isLink:
        description: 是否外链
        type: boolean
      method:
        description: 接口请求方法
        type: integer
      modifier:
        description: 修改人
        type: string
      name:
        description: 组件名称
        type: string
      parent_id:
        description: 上级菜单
        type: string
      path:
        description: 路由地址
        type: string
      permission:
        description: 权限标识
        type: string
      redirect:
        description: 重定向地址
        type: string
      remark:
        description: 备注
        type: string
      sort:
        description: 显示排序
        type: integer
      status:
        description: 状态
        type: boolean
      title:
        description: 菜单标题
        type: string
      type:
        description: 菜单类型
        type: integer
      updateTime:
        description: 更新时间
        type: string
      version:
        description: 版本号
        type: integer
    type: object
  github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User:
    properties:
      avatar:
        description: 头像
        type: string
      belongDept:
        description: 数据归属部门
        type: string
      createTime:
        description: 创建时间
        type: string
      creator:
        description: 创建人
        type: string
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别
        type: integer
      id:
        description: 主键ID
        type: string
      mobile:
        description: 电话
        type: string
      modifier:
        description: 修改人
        type: string
      name:
        description: 姓名
        type: string
      remark:
        description: 备注
        type: string
      sort:
        description: 显示排序
        type: integer
      status:
        description: 状态
        type: integer
      updateTime:
        description: 更新时间
        type: string
      userType:
        description: 用户类型
        type: integer
      username:
        description: 用户名
        type: string
      version:
        description: 版本号
        type: integer
    type: object
  response.Response:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 数据
      msg:
        description: 提示信息
      success:
        description: 是否成功
        type: boolean
    type: object
  third.CaptchaResponse:
    properties:
      code:
        description: 验证码
        type: string
      id:
        description: 验证码Id
        type: string
      img:
        description: 验证码图片
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: 2224693191@qq.com
    name: CJiaの用心
    url: http://www.swagger.io/support
  description: CarefulAdmin在线接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms
  title: CarefulAdmin
  version: "1.0"
paths:
  /v1/auth/change-password:
    post:
      consumes:
      - application/json
      description: 修改当前登录用户的密码
      parameters:
      - description: 修改密码参数
        in: body
        name: ChangePasswordRequest
        required: true
        schema:
          $ref: '#/definitions/auth.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      - LoginToken: []
      summary: 修改密码
      tags:
      - 认证管理
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: 账号密码登录
      parameters:
      - description: 请求
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 账号密码登录
      tags:
      - 认证管理
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: 用户退出登录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      - LoginToken: []
      summary: 退出登录
      tags:
      - 认证管理
  /v1/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: 使用旧的JWT令牌获取新的令牌
      parameters:
      - description: 刷新令牌参数
        in: body
        name: RefreshTokenRequest
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      summary: 刷新令牌
      tags:
      - 认证管理
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 请求
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册
      tags:
      - 认证管理
  /v1/auth/type-login:
    post:
      consumes:
      - application/json
      description: 不同类型用户登录接口
      parameters:
      - description: 多用户类型登录参数
        in: body
        name: UserTypeLoginRequest
        required: true
        schema:
          $ref: '#/definitions/auth.UserTypeLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      summary: 多用户类型登录
      tags:
      - 认证管理
  /v1/auth/userinfo:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      - LoginToken: []
      summary: 获取当前登录用户信息
      tags:
      - 认证管理
  /v1/system/menu/listRouter:
    get:
      consumes:
      - application/json
      description: 获取所有菜单列表
      parameters:
      - default: -1
        description: 状态
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_carefuly_carefuly-admin-go-gin_internal_domain_careful_system.Menu'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 获取所有菜单
      tags:
      - 菜单管理
  /v1/third/generateCaptcha:
    get:
      consumes:
      - application/json
      description: 生成指定业务验证码
      parameters:
      - description: 业务类型
        example: BizCaptchaLogin
        in: query
        name: bizType
        required: true
        type: string
      - description: 验证码类型
        enum:
        - 1
        in: query
        name: type
        required: true
        type: integer
        x-enum-comments:
          DigitIotaCaptcha: 数字字母验证码
        x-enum-varnames:
        - DigitIotaCaptcha
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/third.CaptchaResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 生成指定业务验证码
      tags:
      - 第三方业务管理
securityDefinitions:
  LoginToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
